In [1]:
import pandas as pd 
import numpy as np

In [4]:
df = pd.read_csv("C:/Users/ASUS/OneDrive/Desktop/Data_sets/customer.csv")
df.sample()

    age gender review education purchased
19   97   Male   Poor        PG       Yes

In [7]:
df.isnull().sum()

age          0
gender       0
review       0
education    0
purchased    0
dtype: int64

In [8]:
df.describe()

             age
count  50.000000
mean   54.160000
std    25.658161
min    15.000000
25%    30.250000
50%    57.000000
75%    74.000000
max    98.000000

In [22]:
df.sample(5)

     age  gender   review education purchased
26  53.0     NaN     Poor        PG        No
9   74.0     NaN     Good        UG       Yes
36  34.0     NaN     Good        UG       Yes
34  86.0     NaN  Average    School        No
22  18.0     NaN     Poor        PG       Yes

In [18]:
df['age'] = df['age'].astype(float)

df.dtypes

age          float64
gender       float64
review        object
education     object
purchased     object
dtype: object

In [21]:
df['gender'] = df['gender'].map({'male': 0.0, 'female': 1.1
                                })